### ISSUE TITLE
always missing on the Alphabetical Index

### ISSUE THREAD

**Issue by viboes** [boostorg/hana#276] opened 2016-05-22 21:34 UTC

**Comment by ricejasonf** [comment] 2016-05-22 23:02
What is always missing on the Alphabetical Index? XD

It appears everything in Functional and Core is missing from the Aplahbetical Index as well.

**Comment by viboes** [comment] 2016-05-23 05:07
`hana::always` :).

**Comment by ldionne** [comment] 2016-05-24 20:44
Duplicate of #238.

**Closed by ldionne** 2016-05-24 20:44 UTC
Labels: duplicate
